### PR TITLE
i8 to u8 fix in pam module

### PR DESCRIPTION
**Pull request by appelgriebsch**

### CODE REVIEW

**Comment by kennylevinsen** [comment]
This fix is not correct. I suppose you're trying to build for arm or powerpc where `c_char` is defined as `u8`, but that won't work for x86 where the type is indeed `i8`.

See https://github.com/rust-lang/rust/blob/ef92009c1dbe2750f1d24a6619b827721fb49749/src/libstd/os/raw/mod.rs for rusts' definitions.
 
The correct portable type is `c_char`.

**Comment by kennylevinsen** [comment]
Manually squashed and merged. Thanks!

**Comment by kennylevinsen** [comment]
Btw, you posted this both to lists.sr.ht *and* as pr to github, seemingly simultaneously. You only need to post to lists.sr.ht.

(By pure chance I discovered the PR before the list patch, but I prefer lists.)

**Comment by appelgriebsch** [comment]
Yeah, I just wasn’t sure if my setup is ready for git send-email… So I started with the GH PR as this was the ‘well-known’ territory. Later I thought to give it a try and it worked about pretty well actually…

Kind regards,
Andreas

**Pull request closed without merging**
